name: Build vite and Docker image - push to GitHub packages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build vite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup NPM
        uses: actions/setup-node@v3
        with:
          node-version: '16.10'
      - name: Install Dependencies
        run: npm install
      - name: Execute Vite Build
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-folder
          path: dist

  docker:
    name: Build Docker image
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: dist-folder
          path: dist
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build --tag stromtiger-ms/frontend:latest .
      - name: Push Docker image to GitHub Packages
        run: docker push ghcr.io/stromtiger-ms/frontend:latest
